name: senac_salas
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies: #pacotes para o uso em produção/lançamento
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.8
  drift: ^2.32.1
  drift_flutter: ^0.3.0
  path_provider: ^2.1.5
  path: ^1.9.1
  sqlite3: ^3.2.0
  sqflite_common_ffi_web:
  crypto: ^3.0.7
  intl: ^0.20.2
  brasil_fields: ^1.19.0
  share_plus: ^13.1.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4


dev_dependencies: #pacotes para uso em desenvolvimento
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  drift_dev: ^2.32.1
  build_runner: ^2.13.1


flutter:

  uses-material-design: true

  assets:
    - assets/senac_logo.png
    - assets/splash.png
    - assets/jose.webp
    - assets/kaio.webp
    - assets/logan.webp
    - assets/pedro.webp

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/notosans.ttf
          style: normal 
